#!/usr/bin/env python3
# pylint: disable=invalid-name
import subprocess
import sys
from collections import Counter
from typing import Optional


def get_submodule_paths() -> Optional[set[str]]:
    result = subprocess.run(["git", "submodule", "status"],
                            capture_output=True,
                            text=True,
                            check=True)
    if result.returncode != 0:
        return None
    submodules = []
    for line in result.stdout.splitlines():
        parts = line.split(' ')
        # <space> hash path other
        submodule = ' '.join(parts[2:-1])
        submodules.append(submodule)
    return set(submodules)


def get_file_authors(file: str) -> Optional[Counter[str]]:
    try:
        result = subprocess.run(
            ["git", "blame", "--line-porcelain", "--", file],
            capture_output=True,
            text=True,
            check=True)
    except UnicodeDecodeError:
        # Binary files are not supported
        return None

    if result.returncode != 0:
        return None
    # <commit_hash> 1 1 3
    # author <author>
    # author-mail <<email>>
    # author-time <time>
    # author-tz <tz>
    # committer <commiter>
    # committer-mail <email>
    # committer-time <time>
    # committer-tz <tz>
    # summary <commit message>
    # filename <filename>
    # <code>
    lines = result.stdout.splitlines()
    authors = [
        line[len("author "):] for line in lines if line.startswith("author ")
    ]
    counter = Counter(authors)
    return counter


def main() -> int:
    submodules = get_submodule_paths()
    if submodules is None:
        # Failed to get submodules
        return -1

    git_files_proc = subprocess.run(["git", "ls-files"],
                                    capture_output=True,
                                    text=True,
                                    check=True)
    if git_files_proc.returncode != 0:
        return -2

    author_counts: Counter[str] = Counter()
    for file in filter(lambda f: f not in submodules,
                       git_files_proc.stdout.splitlines()):
        counts = get_file_authors(file)
        if counts is None:
            # TODO: Log
            continue
        author_counts = author_counts + counts

    for author, count in author_counts.most_common():
        print(author, count)
    return 0


if __name__ == "__main__":
    sys.exit(main())
