#! /usr/bin/env bash

pattern=$1

if [[ -z "${pattern}" ]]; then
  echo "Usage: git exclude <pattern>"
  exit 1
fi

exclude_file="$(git config --local core.excludesFile)"
exclude_file="${exclude_file:-$(git rev-parse --git-common-dir)/info/exclude}"

echo "${pattern}" >> "${exclude_file}"
